version: '3'
services:
    
  #  SETUP NODE CONTAINER
  server:
    image: maxbartnitski/server:v9
    expose:
      - "4000"
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - backend
    command: >
      sh -c "sleep 20s && npm run dev"


## SETUP CLIENT CONTAINER
  client: 
    image: maxbartnitski/client:v9
    expose:
      - "5000"
    ports:
      - "5000:5000"
    links:
      - server
    command: npm run docker

  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"

  backend:
    image: maxbartnitski/nosql:v1
    ports:
      - "8080:8080"
    expose:
      - "8080"