version: '3'
services:
    
  #  SETUP NODE CONTAINER
  server:
    image: maxbartnitski/server:v17
    expose:
      - "4000"
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - backend
    env_file:
      - .env
    environment:
      - REDIS_PASS=bear6metal6server
    command: >
      sh -c "sleep 30s && npm run dev"


  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    command: >
      redis-server --requirepass bear6metal6server

  backend:
    image: maxbartnitski/nosql:v5
    ports:
      - "8080:8080"
    expose:
      - "8080" 